### ISSUE TITLE
Android instant run with kotlin coroutines issue

### ISSUE THREAD

**Issue by N-i-p-o-l** [Kotlin/kotlin-coroutines#103]
Description:

`import kotlinx.android.synthetic.main.fragment_filter_date.*`

Filter load function:
```
fun showFilter() {
    runBlocking {
      val filter = merchantRepository.getFilterFields().await()
      view.showFilter(filter) //this run on UI main thread in onViewCreated method
    }
  }
```

**Code before:**
```
filter?.let {
      frag_filter_cardNumber.setText(it.cardNumber)
      it.amount?.let {frag_filter_sum.setText(it.toString())}
      frag_filter_description.setText(it.description)
    }
```

**Code modyfied after:**
```
filter?.let {
      frag_filter_etName.setText(it.account) //**this line is added**
      frag_filter_cardNumber.setText(it.cardNumber)
      it.amount?.let {frag_filter_sum.setText(it.toString())}
      frag_filter_description.setText(it.description)
    }
```

After code is modyfied i run instant run hot swap (CTRL+F10). I got an error. See stacktrace:

```
java.lang.IllegalStateException: frag_filter_etName must not be null                                                                              at uz.paycom.merchantcabinet.ui.filter.FilterDateFragment$override.showAccount(FilterDateFragment.kt:148)
                                                                               at uz.paycom.merchantcabinet.ui.filter.FilterDateFragment$override.access$dispatch(FilterDateFragment.kt)
                                                                               at uz.paycom.merchantcabinet.ui.filter.FilterDateFragment.showAccount(FilterDateFragment.kt:0)
                                                                               at uz.paycom.merchantcabinet.ui.filter.FilterPresenter$showMerchant$1$1.doResume(FilterPresenter.kt:17)
                                                                               at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                               at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                                                                               at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

If I use cold build without instant run it's ok no errors. Error 100% repeatable with hot swap. I don't know what's the problem. Kotlin android extensions, kotlin coroutines or android instant run gives me the error. Please help

**Comment by yole** [comment]
"In this repository, we keep track of the design for coroutines in Kotlin"
Please don't report issues related to the use of coroutines here.

**Comment by elizarov** [comment]
FYI, it suspiciously looks like a duplicate of https://youtrack.jetbrains.com/issue/KT-22267
